const express = require('express');
const router = express.Router();
const pool = require('../db');
const fs = require('fs');
const path = require('path');
const https = require('https');

function triggerDeploy() {
  const token = process.env.GITHUB_DEPLOY_TOKEN;
  const repo = process.env.GITHUB_REPO || 'SairaNawaz/rmsb-dashboard';
  if (!token) return;

  const body = JSON.stringify({ event_type: 'service-deploy' });
  const [owner, repoName] = repo.split('/');
  const req = https.request({
    hostname: 'api.github.com',
    path: `/repos/${owner}/${repoName}/dispatches`,
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      'User-Agent': 'rmsb-api-gateway',
      'Content-Length': Buffer.byteLength(body),
    },
  });
  req.on('error', (err) => console.error('Deploy trigger failed:', err.message));
  req.write(body);
  req.end();
}

// Project root is two levels up from api-gateway/src/
const COMPOSE_PATH = path.resolve(__dirname, '../../../docker-compose.yml');

// GET /registry — list all services
router.get('/', async (req, res) => {
  try {
    const { rows } = await pool.query('SELECT * FROM services ORDER BY registered_at ASC');
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// POST /registry — register a new service
router.post('/', async (req, res) => {
  const {
    name, display_name, description, icon, path_prefix, port,
    container_name, schema_name, repo_url, branch, ghcr_image, image_tag,
  } = req.body;

  try {
    const { rows } = await pool.query(
      `INSERT INTO services
         (name, display_name, description, icon, path_prefix, port,
          container_name, schema_name, repo_url, branch, ghcr_image, image_tag)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
       RETURNING *`,
      [
        name, display_name, description || null, icon || '🔧', path_prefix, port,
        container_name, schema_name, repo_url || null, branch || 'main',
        ghcr_image || null, image_tag || 'latest',
      ]
    );
    res.status(201).json(rows[0]);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// POST /registry/compose-sync — generate and write docker-compose.yml to project root
// Must be declared before /:id to avoid route conflict
router.post('/compose-sync', async (req, res) => {
  try {
    const { rows } = await pool.query(
      `SELECT * FROM services WHERE status != 'disabled' ORDER BY port ASC`
    );
    const yaml = generateComposeYaml(rows);
    fs.writeFileSync(COMPOSE_PATH, yaml, 'utf8');
    console.log(`docker-compose.yml written to ${COMPOSE_PATH}`);
    triggerDeploy();
    res.json({ ok: true, path: COMPOSE_PATH, services: rows.length });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// PATCH /registry/:id — update a service (status, etc.)
router.patch('/:id', async (req, res) => {
  const { status } = req.body;
  try {
    const { rows } = await pool.query(
      `UPDATE services SET status = $1, updated_at = NOW() WHERE id = $2 RETURNING *`,
      [status, req.params.id]
    );
    if (!rows.length) return res.status(404).json({ error: 'Service not found' });
    res.json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// DELETE /registry/:id — remove a service
router.delete('/:id', async (req, res) => {
  try {
    await pool.query('DELETE FROM services WHERE id = $1', [req.params.id]);
    res.status(204).end();
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ─── Compose YAML generator ───────────────────────────────────────────────────

function generateComposeYaml(services) {
  const serviceBlocks = services
    .map(
      (svc) => `
  ${svc.name}:
    image: ${svc.ghcr_image || `ghcr.io/sairanawaz/rmsb-${svc.name}-api`}:${svc.image_tag || 'latest'}
    container_name: ${svc.container_name}
    environment:
      PORT: ${svc.port}
      DB_SCHEMA: ${svc.schema_name}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: \${POSTGRES_USER}
      DB_PASSWORD: \${POSTGRES_PASSWORD}
      DB_NAME: \${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy`
    )
    .join('\n');

  const gatewayEnvRoutes = services
    .map(
      (svc) =>
        `      ${svc.name.toUpperCase()}_SERVICE_URL: http://${svc.name}:${svc.port}`
    )
    .join('\n');

  // Use map syntax for all depends_on entries so we can mix condition types
  const gatewayDeps = services
    .map((svc) => `      ${svc.name}:\n        condition: service_started`)
    .join('\n');

  return `# ─────────────────────────────────────────────────────────
# docker-compose.yml  —  PRODUCTION / CI  (image-based)
# Auto-generated by RMSB Registry — do not edit manually.
# To regenerate: Settings → Services → Sync Compose
# ─────────────────────────────────────────────────────────
version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: rmsb-postgres
    environment:
      POSTGRES_USER: \${POSTGRES_USER}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_DB: \${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER} -d \${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
${serviceBlocks}

  api-gateway:
    image: ghcr.io/sairanawaz/rmsb-api-gateway:\${TAG:-latest}
    container_name: rmsb-api-gateway
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: \${POSTGRES_USER}
      DB_PASSWORD: \${POSTGRES_PASSWORD}
      DB_NAME: \${POSTGRES_DB}
      ADMIN_EMAILS: \${ADMIN_EMAILS}
      GITHUB_DEPLOY_TOKEN: \${GITHUB_DEPLOY_TOKEN}
      GITHUB_REPO: \${GITHUB_REPO:-SairaNawaz/rmsb-dashboard}
      FRONTEND_URL: http://frontend:5173
${gatewayEnvRoutes}
    depends_on:
      postgres:
        condition: service_healthy
${gatewayDeps}

  frontend:
    image: ghcr.io/sairanawaz/rmsb-frontend:\${TAG:-latest}
    container_name: rmsb-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_GATEWAY_URL: http://localhost:8080
    depends_on:
      - api-gateway

volumes:
  postgres_data:
`;
}

module.exports = router;
